services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python main.py 
    volumes:
      - .:/app  # Mount the current directory to the /app directory in the container
    env_file:
      - .env
    ports: 
      - 8080:8080
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
